// Generated from Chubu Electric Power Grid public capacity CSV KRSIH013.
// Source evidence: /Users/isibasidaisuke/WAJO Sales OS/LAND_GRID_CAPACITY_CHUBU_MIE_PUBLIC_JSON_2026-06-14.json

export const chubuMieGridCapacitySnapshot = {
	"generatedAtJst": "2026-06-14 19:12:45 JST",
	"purpose": "中部電力PG公式マップ/CSV ZIPから生成した系統空容量の公表値候補。接続可否の確定ではない。",
	"target": {
		"lat": 34.906456,
		"lon": 136.570953,
		"addressCandidate": "三重県鈴鹿市国分町池ノ谷 52-14"
	},
	"officialSources": {
		"chubuMapGuide": "https://powergrid.chuden.co.jp/goannai/hatsuden_kouri/takuso_kyokyu/rule/map/",
		"chubuMapApp": "https://gridmap.powergrid.chuden.co.jp/",
		"passJson": "https://gridmap.powergrid.chuden.co.jp/pass_data/pass.json",
		"mieCsvZip": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
		"mapData": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH001",
		"mapParameter": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH002"
	},
	"sourceDates": {
		"mieCsvUpdated": "2026年6月8日",
		"mapParameterTaishobi": "2026年06月09日時点"
	},
	"warnings": [
		"中部電力PGは、マッピングが示す空容量は連系容量および接続可否を保証するものではないと明記している。",
		"空容量がある場合でも、故障時の出力制御、N-1電制、変圧器逆潮流対策、工事費負担、接続検討結果で変わる。",
		"このJSONは初回判定の公表値候補であり、接続検討回答書ではない。"
	],
	"data": [
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "神戸変電所",
			"facilityNo": "3703",
			"voltageKv": 77,
			"secondaryVoltageKv": 6.6,
			"availableCapacityMw": 38,
			"operatingCapacityMw": 49,
			"equipmentCapacityMw": 49,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃３。上位系設備=変1、変3601。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 34.884053,
				"lon": 136.575398
			},
			"distanceFromTargetKm": 2.524
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "石薬師変電所",
			"facilityNo": "3701",
			"voltageKv": 77,
			"secondaryVoltageKv": 6.6,
			"availableCapacityMw": 0,
			"operatingCapacityMw": 19,
			"equipmentCapacityMw": 19,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃３。上位系設備=変1、送31175、変3601。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 34.906868,
				"lon": 136.542633
			},
			"distanceFromTargetKm": 2.583
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "大治田町変電所",
			"facilityNo": "3704",
			"voltageKv": 77,
			"secondaryVoltageKv": 6.6,
			"availableCapacityMw": 14,
			"operatingCapacityMw": 19,
			"equipmentCapacityMw": 19,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃３。上位系設備=変1、変3601。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 34.921771,
				"lon": 136.599087
			},
			"distanceFromTargetKm": 3.079
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "北勢変電所(2)",
			"facilityNo": "3708",
			"voltageKv": 77,
			"secondaryVoltageKv": 6.6,
			"availableCapacityMw": 31,
			"operatingCapacityMw": 49,
			"equipmentCapacityMw": 49,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃３。上位系設備=変1、変3601。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 34.943844,
				"lon": 136.594774
			},
			"distanceFromTargetKm": 4.69
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "庄野変電所",
			"facilityNo": "3697",
			"voltageKv": 77,
			"secondaryVoltageKv": 6.6,
			"availableCapacityMw": 37,
			"operatingCapacityMw": 49,
			"equipmentCapacityMw": 49,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃３。上位系設備=変1、変3607。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 34.876845,
				"lon": 136.533976
			},
			"distanceFromTargetKm": 4.713
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "北勢変電所(1)",
			"facilityNo": "3604",
			"voltageKv": 154,
			"secondaryVoltageKv": 77,
			"availableCapacityMw": null,
			"operatingCapacityMw": 510,
			"equipmentCapacityMw": 567,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "可。N-1電制適用可能量=57MW。上位系設備=変1、変3601。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 34.944171,
				"lon": 136.595249
			},
			"distanceFromTargetKm": 4.743
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "末広変電所(1)",
			"facilityNo": "3616",
			"voltageKv": 77,
			"secondaryVoltageKv": 22,
			"availableCapacityMw": null,
			"operatingCapacityMw": 42,
			"equipmentCapacityMw": 57,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "可。N-1電制適用可能量=14MW。上位系設備=変1、変3607。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 34.859164,
				"lon": 136.567701
			},
			"distanceFromTargetKm": 5.267
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "末広変電所(2)",
			"facilityNo": "3695",
			"voltageKv": 77,
			"secondaryVoltageKv": 6.6,
			"availableCapacityMw": 22,
			"operatingCapacityMw": 49,
			"equipmentCapacityMw": 49,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃３。上位系設備=変1、変3607。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 34.859164,
				"lon": 136.566701
			},
			"distanceFromTargetKm": 5.273
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "楠変電所",
			"facilityNo": "3706",
			"voltageKv": 77,
			"secondaryVoltageKv": 6.6,
			"availableCapacityMw": 35,
			"operatingCapacityMw": 49,
			"equipmentCapacityMw": 49,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃３。上位系設備=変1、変3601。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 34.919385,
				"lon": 136.632452
			},
			"distanceFromTargetKm": 5.789
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "玉垣変電所",
			"facilityNo": "3698",
			"voltageKv": 77,
			"secondaryVoltageKv": 6.6,
			"availableCapacityMw": 14,
			"operatingCapacityMw": 19,
			"equipmentCapacityMw": 19,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃３。上位系設備=変1、変3607。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 34.860742,
				"lon": 136.602038
			},
			"distanceFromTargetKm": 5.82
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "四港変電所(1)",
			"facilityNo": "3615",
			"voltageKv": 77,
			"secondaryVoltageKv": 22,
			"availableCapacityMw": null,
			"operatingCapacityMw": 42,
			"equipmentCapacityMw": 57,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "可。N-1電制適用可能量=14MW。上位系設備=変1、変3601。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 34.939862,
				"lon": 136.626728
			},
			"distanceFromTargetKm": 6.297
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "岸田変電所",
			"facilityNo": "3702",
			"voltageKv": 77,
			"secondaryVoltageKv": 6.6,
			"availableCapacityMw": 2,
			"operatingCapacityMw": 49,
			"equipmentCapacityMw": 49,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃３。上位系設備=変1、送31175、変3601。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 34.940306,
				"lon": 136.510497
			},
			"distanceFromTargetKm": 6.674
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "赤堀変電所",
			"facilityNo": "3754",
			"voltageKv": 77,
			"secondaryVoltageKv": 6.6,
			"availableCapacityMw": 49,
			"operatingCapacityMw": 49,
			"equipmentCapacityMw": 49,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃３。上位系設備=変1、変3601。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 34.959039,
				"lon": 136.612841
			},
			"distanceFromTargetKm": 6.983
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "常磐変電所",
			"facilityNo": "3707",
			"voltageKv": 77,
			"secondaryVoltageKv": 6.6,
			"availableCapacityMw": 47,
			"operatingCapacityMw": 49,
			"equipmentCapacityMw": 49,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃３。上位系設備=変1、変3601。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 34.964707,
				"lon": 136.601828
			},
			"distanceFromTargetKm": 7.062
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "住吉町変電所",
			"facilityNo": "3696",
			"voltageKv": 77,
			"secondaryVoltageKv": 6.6,
			"availableCapacityMw": 0,
			"operatingCapacityMw": 19,
			"equipmentCapacityMw": 19,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃３。上位系設備=変1、変3607。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 34.854774,
				"lon": 136.524529
			},
			"distanceFromTargetKm": 7.139
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "能褒野変電所",
			"facilityNo": "3699",
			"voltageKv": 77,
			"secondaryVoltageKv": 6.6,
			"availableCapacityMw": 0,
			"operatingCapacityMw": 49,
			"equipmentCapacityMw": 49,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃３。上位系設備=変1、送31175、変3601。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 34.889265,
				"lon": 136.488896
			},
			"distanceFromTargetKm": 7.724
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "昌栄変電所",
			"facilityNo": "3714",
			"voltageKv": 77,
			"secondaryVoltageKv": 6.6,
			"availableCapacityMw": 49,
			"operatingCapacityMw": 49,
			"equipmentCapacityMw": 49,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃３。上位系設備=変1、変3601。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 34.957675,
				"lon": 136.628851
			},
			"distanceFromTargetKm": 7.765
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "白子変電所",
			"facilityNo": "3759",
			"voltageKv": 77,
			"secondaryVoltageKv": 6.6,
			"availableCapacityMw": 23,
			"operatingCapacityMw": 49,
			"equipmentCapacityMw": 49,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃３。上位系設備=変1、変3607。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 34.831821,
				"lon": 136.575757
			},
			"distanceFromTargetKm": 8.311
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "堀木変電所",
			"facilityNo": "3770",
			"voltageKv": 77,
			"secondaryVoltageKv": 6.6,
			"availableCapacityMw": 19,
			"operatingCapacityMw": 19,
			"equipmentCapacityMw": 19,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃３。上位系設備=変1、変3601。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 34.974858,
				"lon": 136.616397
			},
			"distanceFromTargetKm": 8.661
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "五祝変電所",
			"facilityNo": "3690",
			"voltageKv": 77,
			"secondaryVoltageKv": 6.6,
			"availableCapacityMw": 0,
			"operatingCapacityMw": 19,
			"equipmentCapacityMw": 19,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃３。上位系設備=変1、変3607。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 34.826275,
				"lon": 136.555903
			},
			"distanceFromTargetKm": 9.021
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "北条変電所",
			"facilityNo": "3769",
			"voltageKv": 77,
			"secondaryVoltageKv": 6.6,
			"availableCapacityMw": 19,
			"operatingCapacityMw": 19,
			"equipmentCapacityMw": 19,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃３。上位系設備=変1、変3601。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 34.970623,
				"lon": 136.632067
			},
			"distanceFromTargetKm": 9.052
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "生桑変電所",
			"facilityNo": "3712",
			"voltageKv": 77,
			"secondaryVoltageKv": 6.6,
			"availableCapacityMw": 6,
			"operatingCapacityMw": 19,
			"equipmentCapacityMw": 19,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃３。上位系設備=変1、変3601。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 34.986348,
				"lon": 136.60378
			},
			"distanceFromTargetKm": 9.374
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "桜変電所",
			"facilityNo": "3757",
			"voltageKv": 77,
			"secondaryVoltageKv": 6.6,
			"availableCapacityMw": 3,
			"operatingCapacityMw": 49,
			"equipmentCapacityMw": 49,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃３。上位系設備=変1、変3601。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 34.977694,
				"lon": 136.515048
			},
			"distanceFromTargetKm": 9.419
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "川合変電所",
			"facilityNo": "3700",
			"voltageKv": 77,
			"secondaryVoltageKv": 6.6,
			"availableCapacityMw": 8,
			"operatingCapacityMw": 28,
			"equipmentCapacityMw": 28,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃３。上位系設備=変1、送31175、変3601。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 34.870503,
				"lon": 136.470848
			},
			"distanceFromTargetKm": 9.967
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "四日市火力変電所",
			"facilityNo": "3603",
			"voltageKv": 154,
			"secondaryVoltageKv": 77,
			"availableCapacityMw": null,
			"operatingCapacityMw": 280,
			"equipmentCapacityMw": 373,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "可。N-1電制適用可能量=93MW。上位系設備=変1、変3601。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 34.975509,
				"lon": 136.646233
			},
			"distanceFromTargetKm": 10.298
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "羽津変電所",
			"facilityNo": "3717",
			"voltageKv": 77,
			"secondaryVoltageKv": 6.6,
			"availableCapacityMw": 27,
			"operatingCapacityMw": 28,
			"equipmentCapacityMw": 28,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃３。上位系設備=変1、変3601。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 34.988164,
				"lon": 136.642762
			},
			"distanceFromTargetKm": 11.197
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "平尾変電所",
			"facilityNo": "3711",
			"voltageKv": 77,
			"secondaryVoltageKv": 6.6,
			"availableCapacityMw": 0,
			"operatingCapacityMw": 19,
			"equipmentCapacityMw": 19,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃３。上位系設備=変1、変3601、変3602。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 35.008001,
				"lon": 136.557398
			},
			"distanceFromTargetKm": 11.359
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "霞変電所",
			"facilityNo": "3719",
			"voltageKv": 77,
			"secondaryVoltageKv": 6.6,
			"availableCapacityMw": 16,
			"operatingCapacityMw": 19,
			"equipmentCapacityMw": 19,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃３。上位系設備=変1、変3601。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 34.983589,
				"lon": 136.669878
			},
			"distanceFromTargetKm": 12.444
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "垂坂変電所",
			"facilityNo": "3716",
			"voltageKv": 77,
			"secondaryVoltageKv": 6.6,
			"availableCapacityMw": 14,
			"operatingCapacityMw": 19,
			"equipmentCapacityMw": 19,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃３。上位系設備=変1、変3601。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 35.013028,
				"lon": 136.612864
			},
			"distanceFromTargetKm": 12.451
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "天神町変電所",
			"facilityNo": "3694",
			"voltageKv": 77,
			"secondaryVoltageKv": 6.6,
			"availableCapacityMw": 0,
			"operatingCapacityMw": 19,
			"equipmentCapacityMw": 19,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃３。上位系設備=変1、変3607。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 34.844061,
				"lon": 136.453349
			},
			"distanceFromTargetKm": 12.776
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "河芸変電所",
			"facilityNo": "3689",
			"voltageKv": 77,
			"secondaryVoltageKv": 6.6,
			"availableCapacityMw": 6,
			"operatingCapacityMw": 49,
			"equipmentCapacityMw": 49,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃３。上位系設備=変1、変3607。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 34.789277,
				"lon": 136.538944
			},
			"distanceFromTargetKm": 13.353
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "富田変電所",
			"facilityNo": "3715",
			"voltageKv": 77,
			"secondaryVoltageKv": 6.6,
			"availableCapacityMw": 41,
			"operatingCapacityMw": 49,
			"equipmentCapacityMw": 49,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃３。上位系設備=変1、変3601、変3602。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 35.010655,
				"lon": 136.64576
			},
			"distanceFromTargetKm": 13.443
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "潤田変電所",
			"facilityNo": "3710",
			"voltageKv": 77,
			"secondaryVoltageKv": 6.6,
			"availableCapacityMw": 7,
			"operatingCapacityMw": 28,
			"equipmentCapacityMw": 28,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃３。上位系設備=変1、変3601。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 35.02051,
				"lon": 136.51576
			},
			"distanceFromTargetKm": 13.643
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "新鈴鹿変電所",
			"facilityNo": "3607",
			"voltageKv": 275,
			"secondaryVoltageKv": 77,
			"availableCapacityMw": null,
			"operatingCapacityMw": 640,
			"equipmentCapacityMw": 708,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "可。N-1電制適用可能量=68MW。上位系設備=変1。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 34.840172,
				"lon": 136.437321
			},
			"distanceFromTargetKm": 14.246
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "音羽南変電所",
			"facilityNo": "3709",
			"voltageKv": 77,
			"secondaryVoltageKv": 6.6,
			"availableCapacityMw": 0,
			"operatingCapacityMw": 19,
			"equipmentCapacityMw": 19,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃３。上位系設備=変1、変3601。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 35.025189,
				"lon": 136.491583
			},
			"distanceFromTargetKm": 15.054
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "亀山変電所",
			"facilityNo": "3606",
			"voltageKv": 275,
			"secondaryVoltageKv": 77,
			"availableCapacityMw": null,
			"operatingCapacityMw": 356,
			"equipmentCapacityMw": 475,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "可。N-1電制適用可能量=119MW。上位系設備=変1。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 34.878513,
				"lon": 136.408645
			},
			"distanceFromTargetKm": 15.126
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "高松変電所",
			"facilityNo": "3718",
			"voltageKv": 77,
			"secondaryVoltageKv": 6.6,
			"availableCapacityMw": 48,
			"operatingCapacityMw": 49,
			"equipmentCapacityMw": 49,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃３。上位系設備=変1、変3601、変3602。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 35.017978,
				"lon": 136.666286
			},
			"distanceFromTargetKm": 15.141
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "あのつ台変電所",
			"facilityNo": "3767",
			"voltageKv": 77,
			"secondaryVoltageKv": 6.6,
			"availableCapacityMw": 3,
			"operatingCapacityMw": 19,
			"equipmentCapacityMw": 19,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃３。上位系設備=変1、変3607。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 34.784398,
				"lon": 136.494541
			},
			"distanceFromTargetKm": 15.259
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "川越変電所",
			"facilityNo": "3610",
			"voltageKv": 275,
			"secondaryVoltageKv": 77,
			"availableCapacityMw": null,
			"operatingCapacityMw": 355,
			"equipmentCapacityMw": 474,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "可。N-1電制適用可能量=119MW。上位系設備=変1。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 35.010439,
				"lon": 136.689327
			},
			"distanceFromTargetKm": 15.813
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "古里変電所",
			"facilityNo": "3671",
			"voltageKv": 77,
			"secondaryVoltageKv": 6.6,
			"availableCapacityMw": 21,
			"operatingCapacityMw": 74,
			"equipmentCapacityMw": 74,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃３。上位系設備=変1。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 34.854708,
				"lon": 136.409357
			},
			"distanceFromTargetKm": 15.824
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "竹成変電所",
			"facilityNo": "3760",
			"voltageKv": 77,
			"secondaryVoltageKv": 6.6,
			"availableCapacityMw": 5,
			"operatingCapacityMw": 19,
			"equipmentCapacityMw": 19,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃３。上位系設備=変1、変3601。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 35.040802,
				"lon": 136.512253
			},
			"distanceFromTargetKm": 15.867
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "東員変電所",
			"facilityNo": "3713",
			"voltageKv": 77,
			"secondaryVoltageKv": 6.6,
			"availableCapacityMw": 4,
			"operatingCapacityMw": 49,
			"equipmentCapacityMw": 49,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃３。上位系設備=変1、変3601、変3602。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 35.054725,
				"lon": 136.582716
			},
			"distanceFromTargetKm": 16.522
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "当新田変電所",
			"facilityNo": "3755",
			"voltageKv": 77,
			"secondaryVoltageKv": 6.6,
			"availableCapacityMw": 43,
			"operatingCapacityMw": 49,
			"equipmentCapacityMw": 49,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃３。上位系設備=変1。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 35.029066,
				"lon": 136.684212
			},
			"distanceFromTargetKm": 17.099
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "芸濃変電所",
			"facilityNo": "3691",
			"voltageKv": 77,
			"secondaryVoltageKv": 6.6,
			"availableCapacityMw": 0,
			"operatingCapacityMw": 19,
			"equipmentCapacityMw": 19,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃３。上位系設備=変1、変3607。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 34.800178,
				"lon": 136.433106
			},
			"distanceFromTargetKm": 17.259
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "一身田変電所",
			"facilityNo": "3693",
			"voltageKv": 77,
			"secondaryVoltageKv": 6.6,
			"availableCapacityMw": 10,
			"operatingCapacityMw": 19,
			"equipmentCapacityMw": 19,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃３。上位系設備=変1、送170、送180、変3608。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 34.756865,
				"lon": 136.511966
			},
			"distanceFromTargetKm": 17.483
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "能部変電所",
			"facilityNo": "3720",
			"voltageKv": 77,
			"secondaryVoltageKv": 6.6,
			"availableCapacityMw": 16,
			"operatingCapacityMw": 19,
			"equipmentCapacityMw": 19,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃３。上位系設備=変1、変3601、変3602。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 35.054708,
				"lon": 136.636438
			},
			"distanceFromTargetKm": 17.531
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "内多変電所",
			"facilityNo": "3753",
			"voltageKv": 77,
			"secondaryVoltageKv": 6.6,
			"availableCapacityMw": 0,
			"operatingCapacityMw": 19,
			"equipmentCapacityMw": 19,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃３。上位系設備=変1、変3607。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 34.773459,
				"lon": 136.465648
			},
			"distanceFromTargetKm": 17.637
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "町屋変電所",
			"facilityNo": "3721",
			"voltageKv": 77,
			"secondaryVoltageKv": 6.6,
			"availableCapacityMw": 44,
			"operatingCapacityMw": 49,
			"equipmentCapacityMw": 49,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃３。上位系設備=変1。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 35.044983,
				"lon": 136.674255
			},
			"distanceFromTargetKm": 18.051
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "神田変電所",
			"facilityNo": "3726",
			"voltageKv": 77,
			"secondaryVoltageKv": 6.6,
			"availableCapacityMw": 14,
			"operatingCapacityMw": 28,
			"equipmentCapacityMw": 28,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃３。上位系設備=変1、変3601、変3602。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 35.081379,
				"lon": 136.592675
			},
			"distanceFromTargetKm": 19.551
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "城南変電所",
			"facilityNo": "3722",
			"voltageKv": 77,
			"secondaryVoltageKv": 6.6,
			"availableCapacityMw": 24,
			"operatingCapacityMw": 28,
			"equipmentCapacityMw": 28,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃３。上位系設備=変1。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 35.0507,
				"lon": 136.693983
			},
			"distanceFromTargetKm": 19.568
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "橋北変電所",
			"facilityNo": "3688",
			"voltageKv": 77,
			"secondaryVoltageKv": 6.6,
			"availableCapacityMw": 44,
			"operatingCapacityMw": 49,
			"equipmentCapacityMw": 49,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃３。上位系設備=変1、送170、送180、変3608。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 34.734939,
				"lon": 136.514673
			},
			"distanceFromTargetKm": 19.752
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "西名古屋変電所(2)",
			"facilityNo": "3602",
			"voltageKv": 154,
			"secondaryVoltageKv": 77,
			"availableCapacityMw": null,
			"operatingCapacityMw": 466,
			"equipmentCapacityMw": 560,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "可。N-1電制適用可能量=53MW。上位系設備=変1、変3601。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 35.083518,
				"lon": 136.612917
			},
			"distanceFromTargetKm": 20.056
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "西名古屋変電所(1)",
			"facilityNo": "3601",
			"voltageKv": 275,
			"secondaryVoltageKv": 154,
			"availableCapacityMw": null,
			"operatingCapacityMw": 1275,
			"equipmentCapacityMw": 1690,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "可。N-1電制適用可能量=427MW。上位系設備=変1。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 35.083631,
				"lon": 136.614533
			},
			"distanceFromTargetKm": 20.097
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "中央町変電所",
			"facilityNo": "3765",
			"voltageKv": 77,
			"secondaryVoltageKv": 6.6,
			"availableCapacityMw": 49,
			"operatingCapacityMw": 49,
			"equipmentCapacityMw": 49,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃３。上位系設備=変1。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 35.060615,
				"lon": 136.68793
			},
			"distanceFromTargetKm": 20.184
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "渋見変電所",
			"facilityNo": "3692",
			"voltageKv": 77,
			"secondaryVoltageKv": 6.6,
			"availableCapacityMw": 30,
			"operatingCapacityMw": 49,
			"equipmentCapacityMw": 49,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃３。上位系設備=変1、送170、送180、変3608。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 34.736007,
				"lon": 136.493866
			},
			"distanceFromTargetKm": 20.217
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "大山田変電所",
			"facilityNo": "3724",
			"voltageKv": 77,
			"secondaryVoltageKv": 6.6,
			"availableCapacityMw": 33,
			"operatingCapacityMw": 43,
			"equipmentCapacityMw": 43,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃３。上位系設備=変1、変3601、変3602。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 35.085871,
				"lon": 136.632967
			},
			"distanceFromTargetKm": 20.734
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "桑名変電所",
			"facilityNo": "3731",
			"voltageKv": 77,
			"secondaryVoltageKv": 6.6,
			"availableCapacityMw": 49,
			"operatingCapacityMw": 49,
			"equipmentCapacityMw": 49,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃３。上位系設備=変1。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 35.072554,
				"lon": 136.685599
			},
			"distanceFromTargetKm": 21.218
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "播磨変電所",
			"facilityNo": "3730",
			"voltageKv": 77,
			"secondaryVoltageKv": 6.6,
			"availableCapacityMw": 46,
			"operatingCapacityMw": 49,
			"equipmentCapacityMw": 49,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃３。上位系設備=変1。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 35.079492,
				"lon": 136.672624
			},
			"distanceFromTargetKm": 21.354
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "東丸之内変電所",
			"facilityNo": "3676",
			"voltageKv": 77,
			"secondaryVoltageKv": 6.6,
			"availableCapacityMw": 49,
			"operatingCapacityMw": 49,
			"equipmentCapacityMw": 49,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃３。上位系設備=変1、変3607。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 34.716,
				"lon": 136.514034
			},
			"distanceFromTargetKm": 21.806
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "福豊変電所",
			"facilityNo": "3732",
			"voltageKv": 77,
			"secondaryVoltageKv": 6.6,
			"availableCapacityMw": 17,
			"operatingCapacityMw": 19,
			"equipmentCapacityMw": 19,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃３。上位系設備=変1、送10181、変3601。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 35.063291,
				"lon": 136.721044
			},
			"distanceFromTargetKm": 22.161
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "古河変電所",
			"facilityNo": "3673",
			"voltageKv": 77,
			"secondaryVoltageKv": 6.6,
			"availableCapacityMw": 42,
			"operatingCapacityMw": 49,
			"equipmentCapacityMw": 49,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃３。上位系設備=変1、送170、送180、変3608。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 34.713145,
				"lon": 136.500287
			},
			"distanceFromTargetKm": 22.443
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "員弁変電所",
			"facilityNo": "3727",
			"voltageKv": 77,
			"secondaryVoltageKv": 6.6,
			"availableCapacityMw": 3,
			"operatingCapacityMw": 19,
			"equipmentCapacityMw": 19,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃３。上位系設備=変1、変3601、変3602。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 35.109146,
				"lon": 136.576709
			},
			"distanceFromTargetKm": 22.544
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "津変電所",
			"facilityNo": "3614",
			"voltageKv": 77,
			"secondaryVoltageKv": 22,
			"availableCapacityMw": null,
			"operatingCapacityMw": 14,
			"equipmentCapacityMw": 28,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "可。N-1電制適用可能量=14MW。上位系設備=変1、変3607。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 34.715707,
				"lon": 136.485125
			},
			"distanceFromTargetKm": 22.611
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "大安変電所",
			"facilityNo": "3728",
			"voltageKv": 77,
			"secondaryVoltageKv": 6.6,
			"availableCapacityMw": 0,
			"operatingCapacityMw": 19,
			"equipmentCapacityMw": 19,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃３。上位系設備=変1、変3601、変3602。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 35.112019,
				"lon": 136.54277
			},
			"distanceFromTargetKm": 23.001
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "多度変電所",
			"facilityNo": "3723",
			"voltageKv": 77,
			"secondaryVoltageKv": 6.6,
			"availableCapacityMw": 20,
			"operatingCapacityMw": 28,
			"equipmentCapacityMw": 28,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃３。上位系設備=変1、変3601、変3602。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 35.125195,
				"lon": 136.643761
			},
			"distanceFromTargetKm": 25.21
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "藤方変電所",
			"facilityNo": "3674",
			"voltageKv": 77,
			"secondaryVoltageKv": 6.6,
			"availableCapacityMw": 34,
			"operatingCapacityMw": 49,
			"equipmentCapacityMw": 49,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃３。上位系設備=変1、送170、送180、変3608。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 34.681305,
				"lon": 136.513941
			},
			"distanceFromTargetKm": 25.571
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "中勢変電所",
			"facilityNo": "3608",
			"voltageKv": 275,
			"secondaryVoltageKv": 77,
			"availableCapacityMw": null,
			"operatingCapacityMw": 618,
			"equipmentCapacityMw": 712,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "可。N-1電制適用可能量=0MW。上位系設備=変1、送170、送180。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 34.715665,
				"lon": 136.405976
			},
			"distanceFromTargetKm": 26.018
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "美里変電所",
			"facilityNo": "3667",
			"voltageKv": 77,
			"secondaryVoltageKv": 6.6,
			"availableCapacityMw": 2,
			"operatingCapacityMw": 19,
			"equipmentCapacityMw": 19,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃３。上位系設備=変1、送170、送180、変3608。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 34.714414,
				"lon": 136.40526
			},
			"distanceFromTargetKm": 26.169
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "雲出変電所",
			"facilityNo": "3675",
			"voltageKv": 77,
			"secondaryVoltageKv": 6.6,
			"availableCapacityMw": 0,
			"operatingCapacityMw": 19,
			"equipmentCapacityMw": 19,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃３。上位系設備=変1、送170、送180、変3608。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 34.668913,
				"lon": 136.536878
			},
			"distanceFromTargetKm": 26.596
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "六石変電所",
			"facilityNo": "3729",
			"voltageKv": 77,
			"secondaryVoltageKv": 6.6,
			"availableCapacityMw": 2,
			"operatingCapacityMw": 19,
			"equipmentCapacityMw": 19,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃３。上位系設備=変1、変3601、変3602。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 35.145497,
				"lon": 136.527232
			},
			"distanceFromTargetKm": 26.877
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "久居変電所",
			"facilityNo": "3680",
			"voltageKv": 77,
			"secondaryVoltageKv": 6.6,
			"availableCapacityMw": 29,
			"operatingCapacityMw": 49,
			"equipmentCapacityMw": 49,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃３。上位系設備=変1、送170、送180、変3608。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 34.668562,
				"lon": 136.493578
			},
			"distanceFromTargetKm": 27.38
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "羽野変電所",
			"facilityNo": "3682",
			"voltageKv": 77,
			"secondaryVoltageKv": 6.6,
			"availableCapacityMw": 32,
			"operatingCapacityMw": 74,
			"equipmentCapacityMw": 74,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃３。上位系設備=変1、送170、送180、変3608。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 34.680829,
				"lon": 136.443372
			},
			"distanceFromTargetKm": 27.662
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "藤原変電所",
			"facilityNo": "3725",
			"voltageKv": 77,
			"secondaryVoltageKv": 6.6,
			"availableCapacityMw": 0,
			"operatingCapacityMw": 49,
			"equipmentCapacityMw": 49,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃３。上位系設備=変1、送32020、変3601、変3602。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 35.167585,
				"lon": 136.502866
			},
			"distanceFromTargetKm": 29.691
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "三雲変電所",
			"facilityNo": "3672",
			"voltageKv": 77,
			"secondaryVoltageKv": 6.6,
			"availableCapacityMw": 10,
			"operatingCapacityMw": 32,
			"equipmentCapacityMw": 32,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃３。上位系設備=変1、送170、送180、変3608。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 34.636301,
				"lon": 136.507796
			},
			"distanceFromTargetKm": 30.589
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "天花寺変電所",
			"facilityNo": "3655",
			"voltageKv": 154,
			"secondaryVoltageKv": 6.6,
			"availableCapacityMw": 13,
			"operatingCapacityMw": 42,
			"equipmentCapacityMw": 42,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃３。上位系設備=変1、送30034、変3601。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 34.637498,
				"lon": 136.45174
			},
			"distanceFromTargetKm": 31.827
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "二本木変電所",
			"facilityNo": "3665",
			"voltageKv": 77,
			"secondaryVoltageKv": 6.6,
			"availableCapacityMw": 0,
			"operatingCapacityMw": 19,
			"equipmentCapacityMw": 19,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃３。上位系設備=変1、送170、送180、送31471、変3608、送39990。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 34.659687,
				"lon": 136.369772
			},
			"distanceFromTargetKm": 33.023
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "二本木変電所(1)",
			"facilityNo": "3998",
			"voltageKv": 6,
			"secondaryVoltageKv": 22,
			"availableCapacityMw": null,
			"operatingCapacityMw": 5,
			"equipmentCapacityMw": 5,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "可。N-1電制適用可能量=0MW。上位系設備=変1、送170、送180、送31471、変3608、送39990。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 34.659921,
				"lon": 136.368114
			},
			"distanceFromTargetKm": 33.086
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "柏野変電所",
			"facilityNo": "3670",
			"voltageKv": 77,
			"secondaryVoltageKv": 6.6,
			"availableCapacityMw": 0,
			"operatingCapacityMw": 28,
			"equipmentCapacityMw": 28,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃３。上位系設備=変1、送32340、変3607。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 34.816086,
				"lon": 136.197835
			},
			"distanceFromTargetKm": 35.495
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "鎌田変電所",
			"facilityNo": "3677",
			"voltageKv": 77,
			"secondaryVoltageKv": 6.6,
			"availableCapacityMw": 27,
			"operatingCapacityMw": 38,
			"equipmentCapacityMw": 38,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃３。上位系設備=変1、送170、送180、変3611。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 34.587091,
				"lon": 136.540413
			},
			"distanceFromTargetKm": 35.621
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "川原変電所",
			"facilityNo": "3668",
			"voltageKv": 77,
			"secondaryVoltageKv": 6.6,
			"availableCapacityMw": 1,
			"operatingCapacityMw": 19,
			"equipmentCapacityMw": 19,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃３。上位系設備=変1、送170、送180、送31570、変3608。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 34.77028,
				"lon": 136.201024
			},
			"distanceFromTargetKm": 37.002
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "五曲変電所",
			"facilityNo": "3681",
			"voltageKv": 77,
			"secondaryVoltageKv": 6.6,
			"availableCapacityMw": 34,
			"operatingCapacityMw": 49,
			"equipmentCapacityMw": 49,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃３。上位系設備=変1、送30034、変3601。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 34.574098,
				"lon": 136.515714
			},
			"distanceFromTargetKm": 37.3
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "東沢変電所",
			"facilityNo": "3678",
			"voltageKv": 77,
			"secondaryVoltageKv": 6.6,
			"availableCapacityMw": 8,
			"operatingCapacityMw": 49,
			"equipmentCapacityMw": 49,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃３。上位系設備=変1、送170、送180、変3611。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 34.565807,
				"lon": 136.559114
			},
			"distanceFromTargetKm": 37.894
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "佐那具変電所",
			"facilityNo": "3669",
			"voltageKv": 77,
			"secondaryVoltageKv": 6.6,
			"availableCapacityMw": 22,
			"operatingCapacityMw": 49,
			"equipmentCapacityMw": 49,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃３。上位系設備=変1、送31360、送32061、送32340、変3607。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 34.797213,
				"lon": 136.173173
			},
			"distanceFromTargetKm": 38.276
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "松阪変電所",
			"facilityNo": "3679",
			"voltageKv": 77,
			"secondaryVoltageKv": 6.6,
			"availableCapacityMw": 39,
			"operatingCapacityMw": 49,
			"equipmentCapacityMw": 49,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃３。上位系設備=変1、送170、送180、変3611。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 34.56167,
				"lon": 136.531807
			},
			"distanceFromTargetKm": 38.505
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "南勢変電所(2)",
			"facilityNo": "3611",
			"voltageKv": 275,
			"secondaryVoltageKv": 77,
			"availableCapacityMw": null,
			"operatingCapacityMw": 843,
			"equipmentCapacityMw": 936,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "可。N-1電制適用可能量=84MW。上位系設備=変1、送170、送180。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 34.545514,
				"lon": 136.540348
			},
			"distanceFromTargetKm": 40.232
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "南勢変電所(1)",
			"facilityNo": "3609",
			"voltageKv": 154,
			"secondaryVoltageKv": 77,
			"availableCapacityMw": null,
			"operatingCapacityMw": 202,
			"equipmentCapacityMw": 285,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "可。N-1電制適用可能量=83MW。上位系設備=変1、送30034、変3601。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 34.545604,
				"lon": 136.537132
			},
			"distanceFromTargetKm": 40.244
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "荒木変電所",
			"facilityNo": "3666",
			"voltageKv": 77,
			"secondaryVoltageKv": 6.6,
			"availableCapacityMw": 2,
			"operatingCapacityMw": 19,
			"equipmentCapacityMw": 19,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃３。上位系設備=変1、送31360、送32340、変3607。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 34.764955,
				"lon": 136.161386
			},
			"distanceFromTargetKm": 40.557
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "美杉変電所",
			"facilityNo": "3664",
			"voltageKv": 77,
			"secondaryVoltageKv": 6.6,
			"availableCapacityMw": 0,
			"operatingCapacityMw": 19,
			"equipmentCapacityMw": 19,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃３。上位系設備=変1、送170、送180、送31230、送31471、変3608、送39990。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 34.607469,
				"lon": 136.31301
			},
			"distanceFromTargetKm": 40.75
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "斉宮変電所",
			"facilityNo": "3687",
			"voltageKv": 77,
			"secondaryVoltageKv": 6.6,
			"availableCapacityMw": 0,
			"operatingCapacityMw": 38,
			"equipmentCapacityMw": 38,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃３。上位系設備=変1、送170、送180、送31524、送31630、変3611。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 34.538228,
				"lon": 136.629544
			},
			"distanceFromTargetKm": 41.294
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "ゆめが丘変電所",
			"facilityNo": "3766",
			"voltageKv": 77,
			"secondaryVoltageKv": 6.6,
			"availableCapacityMw": 20,
			"operatingCapacityMw": 34,
			"equipmentCapacityMw": 34,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃３。上位系設備=変1、送31353、送31360、送32340、変3607。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 34.730389,
				"lon": 136.168847
			},
			"distanceFromTargetKm": 41.602
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "広陽変電所",
			"facilityNo": "3686",
			"voltageKv": 77,
			"secondaryVoltageKv": 6.6,
			"availableCapacityMw": 3,
			"operatingCapacityMw": 43,
			"equipmentCapacityMw": 43,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃３。上位系設備=変1、送170、送180、変3611。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 34.531637,
				"lon": 136.521286
			},
			"distanceFromTargetKm": 41.924
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "西豊浜変電所",
			"facilityNo": "3736",
			"voltageKv": 77,
			"secondaryVoltageKv": 6.6,
			"availableCapacityMw": 2,
			"operatingCapacityMw": 19,
			"equipmentCapacityMw": 19,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃３。上位系設備=変1、送170、送180、送31372、変3611。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 34.527658,
				"lon": 136.677227
			},
			"distanceFromTargetKm": 43.226
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "上野変電所",
			"facilityNo": "3662",
			"voltageKv": 77,
			"secondaryVoltageKv": 6.6,
			"availableCapacityMw": 22,
			"operatingCapacityMw": 49,
			"equipmentCapacityMw": 49,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃３。上位系設備=変1、送31353、送31360、送32340、変3607。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 34.764821,
				"lon": 136.123854
			},
			"distanceFromTargetKm": 43.74
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "青山変電所",
			"facilityNo": "3660",
			"voltageKv": 77,
			"secondaryVoltageKv": 6.6,
			"availableCapacityMw": 0,
			"operatingCapacityMw": 19,
			"equipmentCapacityMw": 19,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃３。上位系設備=変1、送170、送180、変3608、送39990。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 34.670898,
				"lon": 136.187019
			},
			"distanceFromTargetKm": 43.764
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "四十九変電所",
			"facilityNo": "3663",
			"voltageKv": 77,
			"secondaryVoltageKv": 6.6,
			"availableCapacityMw": 25,
			"operatingCapacityMw": 38,
			"equipmentCapacityMw": 38,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃３。上位系設備=変1、送31353、送31360、送32340、変3607。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 34.747496,
				"lon": 136.132013
			},
			"distanceFromTargetKm": 43.791
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "多気変電所",
			"facilityNo": "3737",
			"voltageKv": 77,
			"secondaryVoltageKv": 6.6,
			"availableCapacityMw": 0,
			"operatingCapacityMw": 19,
			"equipmentCapacityMw": 19,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃３。上位系設備=変1、送170、送180、送31282、送32433、変3611。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 34.50098,
				"lon": 136.557485
			},
			"distanceFromTargetKm": 45.104
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "湯田野変電所",
			"facilityNo": "3735",
			"voltageKv": 77,
			"secondaryVoltageKv": 6.6,
			"availableCapacityMw": 39,
			"operatingCapacityMw": 49,
			"equipmentCapacityMw": 49,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃３。上位系設備=変1、送170、送180、送31372、変3611。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 34.504012,
				"lon": 136.668743
			},
			"distanceFromTargetKm": 45.634
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "田丸変電所",
			"facilityNo": "3734",
			"voltageKv": 77,
			"secondaryVoltageKv": 6.6,
			"availableCapacityMw": 0,
			"operatingCapacityMw": 28,
			"equipmentCapacityMw": 28,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃３。上位系設備=変1、送170、送180、送31372、変3611。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 34.494933,
				"lon": 136.628261
			},
			"distanceFromTargetKm": 46.058
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "山田変電所(2)",
			"facilityNo": "3733",
			"voltageKv": 77,
			"secondaryVoltageKv": 6.6,
			"availableCapacityMw": 38,
			"operatingCapacityMw": 49,
			"equipmentCapacityMw": 49,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃３。上位系設備=変1、送170、送180、送31282、変3611。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 34.508372,
				"lon": 136.716555
			},
			"distanceFromTargetKm": 46.223
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "山田変電所(1)",
			"facilityNo": "3613",
			"voltageKv": 77,
			"secondaryVoltageKv": 22,
			"availableCapacityMw": null,
			"operatingCapacityMw": 9,
			"equipmentCapacityMw": 9,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃２。上位系設備=変1、送170、送180、送31372、変3611。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 34.508368,
				"lon": 136.718074
			},
			"distanceFromTargetKm": 46.263
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "度会橋変電所",
			"facilityNo": "3738",
			"voltageKv": 77,
			"secondaryVoltageKv": 6.6,
			"availableCapacityMw": 36,
			"operatingCapacityMw": 49,
			"equipmentCapacityMw": 49,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃３。上位系設備=変1、送170、送180、送31524、変3611。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 34.493098,
				"lon": 136.688978
			},
			"distanceFromTargetKm": 47.213
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "外宮前変電所",
			"facilityNo": "3756",
			"voltageKv": 77,
			"secondaryVoltageKv": 6.6,
			"availableCapacityMw": 49,
			"operatingCapacityMw": 49,
			"equipmentCapacityMw": 49,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃３。上位系設備=変1、送170、送180、送31524、変3611。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 34.490622,
				"lon": 136.704471
			},
			"distanceFromTargetKm": 47.823
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "通町変電所",
			"facilityNo": "3743",
			"voltageKv": 77,
			"secondaryVoltageKv": 6.6,
			"availableCapacityMw": 3,
			"operatingCapacityMw": 19,
			"equipmentCapacityMw": 19,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃３。上位系設備=変1、送170、送180、送31372、変3611。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 34.499553,
				"lon": 136.74903
			},
			"distanceFromTargetKm": 48.085
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "塩江変電所",
			"facilityNo": "3742",
			"voltageKv": 77,
			"secondaryVoltageKv": 6.6,
			"availableCapacityMw": 38,
			"operatingCapacityMw": 38,
			"equipmentCapacityMw": 38,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃３。上位系設備=変1、送170、送180、送31372、変3611。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 34.491318,
				"lon": 136.722307
			},
			"distanceFromTargetKm": 48.19
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "白樫変電所",
			"facilityNo": "3661",
			"voltageKv": 77,
			"secondaryVoltageKv": 6.6,
			"availableCapacityMw": 0,
			"operatingCapacityMw": 19,
			"equipmentCapacityMw": 19,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃３。上位系設備=変1、送31353、送31360、送32211、送32340、変3607。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 34.727685,
				"lon": 136.08966
			},
			"distanceFromTargetKm": 48.224
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "片野変電所",
			"facilityNo": "3685",
			"voltageKv": 77,
			"secondaryVoltageKv": 6.6,
			"availableCapacityMw": 3,
			"operatingCapacityMw": 43,
			"equipmentCapacityMw": 43,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃３。上位系設備=変1、送30034、送31722、変3601。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 34.481629,
				"lon": 136.452132
			},
			"distanceFromTargetKm": 48.472
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "上小波田変電所",
			"facilityNo": "3659",
			"voltageKv": 77,
			"secondaryVoltageKv": 6.6,
			"availableCapacityMw": 28,
			"operatingCapacityMw": 49,
			"equipmentCapacityMw": 49,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃３。上位系設備=変1、送170、送180、変3608、送39990。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 34.645313,
				"lon": 136.134352
			},
			"distanceFromTargetKm": 49.329
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "予野変電所",
			"facilityNo": "3758",
			"voltageKv": 77,
			"secondaryVoltageKv": 6.6,
			"availableCapacityMw": 3,
			"operatingCapacityMw": 19,
			"equipmentCapacityMw": 19,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃３。上位系設備=変1、送31353、送31360、送32211、送32340、変3607。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 34.713613,
				"lon": 136.083448
			},
			"distanceFromTargetKm": 49.404
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "夏秋変電所",
			"facilityNo": "3658",
			"voltageKv": 77,
			"secondaryVoltageKv": 6.6,
			"availableCapacityMw": 16,
			"operatingCapacityMw": 19,
			"equipmentCapacityMw": 19,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃３。上位系設備=変1、送170、送180、変3608、送39990。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 34.647104,
				"lon": 136.098384
			},
			"distanceFromTargetKm": 51.909
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "栃原変電所",
			"facilityNo": "3651",
			"voltageKv": 154,
			"secondaryVoltageKv": 6.6,
			"availableCapacityMw": 0,
			"operatingCapacityMw": 28,
			"equipmentCapacityMw": 28,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃３。上位系設備=変1、送30034、送30043、変3601。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 34.438933,
				"lon": 136.501833
			},
			"distanceFromTargetKm": 52.369
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "堅神変電所",
			"facilityNo": "3740",
			"voltageKv": 77,
			"secondaryVoltageKv": 6.6,
			"availableCapacityMw": 11,
			"operatingCapacityMw": 19,
			"equipmentCapacityMw": 19,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃３。上位系設備=変1、送170、送180、送31282、変3611。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 34.481761,
				"lon": 136.82021
			},
			"distanceFromTargetKm": 52.435
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "名張変電所",
			"facilityNo": "3657",
			"voltageKv": 77,
			"secondaryVoltageKv": 6.6,
			"availableCapacityMw": 47,
			"operatingCapacityMw": 49,
			"equipmentCapacityMw": 49,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃３。上位系設備=変1、送170、送180、変3608、送39990。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 34.629726,
				"lon": 136.105236
			},
			"distanceFromTargetKm": 52.502
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "瀬古口変電所",
			"facilityNo": "3656",
			"voltageKv": 77,
			"secondaryVoltageKv": 6.6,
			"availableCapacityMw": 19,
			"operatingCapacityMw": 28,
			"equipmentCapacityMw": 28,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃３。上位系設備=変1、送170、送180、変3608、送39990。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 34.617121,
				"lon": 136.085884
			},
			"distanceFromTargetKm": 54.759
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "鳥羽変電所",
			"facilityNo": "3739",
			"voltageKv": 77,
			"secondaryVoltageKv": 6.6,
			"availableCapacityMw": 8,
			"operatingCapacityMw": 28,
			"equipmentCapacityMw": 28,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃３。上位系設備=変1、送170、送180、送31282、送31301、変3611。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 34.464551,
				"lon": 136.838674
			},
			"distanceFromTargetKm": 54.897
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "飯高変電所",
			"facilityNo": "3684",
			"voltageKv": 77,
			"secondaryVoltageKv": 6.6,
			"availableCapacityMw": 0,
			"operatingCapacityMw": 9,
			"equipmentCapacityMw": 9,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃３。上位系設備=変1、送30034、送31722、変3601。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 34.426469,
				"lon": 136.327304
			},
			"distanceFromTargetKm": 57.837
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "滝原変電所",
			"facilityNo": "3652",
			"voltageKv": 154,
			"secondaryVoltageKv": 6.6,
			"availableCapacityMw": 1,
			"operatingCapacityMw": 28,
			"equipmentCapacityMw": 28,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃３。上位系設備=変1、送30034、送30043、変3601。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 34.379105,
				"lon": 136.418336
			},
			"distanceFromTargetKm": 60.278
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "五ヶ所変電所",
			"facilityNo": "3763",
			"voltageKv": 77,
			"secondaryVoltageKv": 6.6,
			"availableCapacityMw": 13,
			"operatingCapacityMw": 19,
			"equipmentCapacityMw": 19,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃３。上位系設備=変1、送170、送180、送31524、送32482、送32510、変3611。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 34.347763,
				"lon": 136.688506
			},
			"distanceFromTargetKm": 63.048
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "磯部変電所",
			"facilityNo": "3741",
			"voltageKv": 77,
			"secondaryVoltageKv": 6.6,
			"availableCapacityMw": 0,
			"operatingCapacityMw": 19,
			"equipmentCapacityMw": 19,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃３。上位系設備=変1、送170、送180、送31372、変3611。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 34.370338,
				"lon": 136.798638
			},
			"distanceFromTargetKm": 63.148
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "相差変電所",
			"facilityNo": "3744",
			"voltageKv": 77,
			"secondaryVoltageKv": 6.6,
			"availableCapacityMw": 0,
			"operatingCapacityMw": 19,
			"equipmentCapacityMw": 19,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃３。上位系設備=変1、送170、送180、送31372、送31502、変3611。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 34.396098,
				"lon": 136.894127
			},
			"distanceFromTargetKm": 63.987
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "押淵変電所",
			"facilityNo": "3762",
			"voltageKv": 77,
			"secondaryVoltageKv": 6.6,
			"availableCapacityMw": 2,
			"operatingCapacityMw": 11,
			"equipmentCapacityMw": 11,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃３。上位系設備=変1、送170、送180、送31524、送32482、送32510、送32520、変3611。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 34.331428,
				"lon": 136.629877
			},
			"distanceFromTargetKm": 64.167
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "森変電所",
			"facilityNo": "3683",
			"voltageKv": 77,
			"secondaryVoltageKv": 6.6,
			"availableCapacityMw": 8,
			"operatingCapacityMw": 19,
			"equipmentCapacityMw": 19,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃３。上位系設備=変1、送30034、送31722、変3601。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 34.400697,
				"lon": 136.218659
			},
			"distanceFromTargetKm": 64.816
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "鵜方変電所",
			"facilityNo": "3752",
			"voltageKv": 77,
			"secondaryVoltageKv": 6.6,
			"availableCapacityMw": 0,
			"operatingCapacityMw": 19,
			"equipmentCapacityMw": 19,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃３。上位系設備=変1、送170、送180、送31372、変3611。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 34.338308,
				"lon": 136.816571
			},
			"distanceFromTargetKm": 67.054
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "浜島変電所",
			"facilityNo": "3761",
			"voltageKv": 77,
			"secondaryVoltageKv": 6.6,
			"availableCapacityMw": 12,
			"operatingCapacityMw": 19,
			"equipmentCapacityMw": 19,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃３。上位系設備=変1、送170、送180、送31524、送32482、変3611。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 34.309075,
				"lon": 136.756663
			},
			"distanceFromTargetKm": 68.566
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "南島変電所",
			"facilityNo": "3653",
			"voltageKv": 154,
			"secondaryVoltageKv": 6.6,
			"availableCapacityMw": 4,
			"operatingCapacityMw": 14,
			"equipmentCapacityMw": 14,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃３。上位系設備=変1、送30034、送30043、変3601。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 34.28237,
				"lon": 136.498232
			},
			"distanceFromTargetKm": 69.714
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "紀勢変電所",
			"facilityNo": "3654",
			"voltageKv": 154,
			"secondaryVoltageKv": 6.6,
			"availableCapacityMw": 1,
			"operatingCapacityMw": 9,
			"equipmentCapacityMw": 9,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃３。上位系設備=変1、送30034、送30043、変3601。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 34.270668,
				"lon": 136.401835
			},
			"distanceFromTargetKm": 72.372
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "立神変電所",
			"facilityNo": "3745",
			"voltageKv": 77,
			"secondaryVoltageKv": 6.6,
			"availableCapacityMw": 0,
			"operatingCapacityMw": 28,
			"equipmentCapacityMw": 28,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃３。上位系設備=変1、送170、送180、送31372、変3611。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 34.302251,
				"lon": 136.870614
			},
			"distanceFromTargetKm": 72.567
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "片田変電所",
			"facilityNo": "3746",
			"voltageKv": 77,
			"secondaryVoltageKv": 6.6,
			"availableCapacityMw": 11,
			"operatingCapacityMw": 19,
			"equipmentCapacityMw": 19,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃３。上位系設備=変1、送170、送180、送31372、変3611。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 34.255006,
				"lon": 136.83669
			},
			"distanceFromTargetKm": 76.414
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "長島変電所",
			"facilityNo": "3751",
			"voltageKv": 77,
			"secondaryVoltageKv": 6.6,
			"availableCapacityMw": 7,
			"operatingCapacityMw": 28,
			"equipmentCapacityMw": 28,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃３。上位系設備=変1、送170、送180、送31760。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 34.206942,
				"lon": 136.329173
			},
			"distanceFromTargetKm": 80.872
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "相賀変電所",
			"facilityNo": "3750",
			"voltageKv": 77,
			"secondaryVoltageKv": 6.6,
			"availableCapacityMw": 0,
			"operatingCapacityMw": 19,
			"equipmentCapacityMw": 19,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃３。上位系設備=変1、送170、送180、送31760。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 34.118129,
				"lon": 136.218796
			},
			"distanceFromTargetKm": 93.408
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "宮ノ上変電所",
			"facilityNo": "3749",
			"voltageKv": 77,
			"secondaryVoltageKv": 6.6,
			"availableCapacityMw": 19,
			"operatingCapacityMw": 19,
			"equipmentCapacityMw": 19,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃３。上位系設備=変1、送170、送180、送31760。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 34.07995,
				"lon": 136.193833
			},
			"distanceFromTargetKm": 98.187
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "尾鷲変電所",
			"facilityNo": "3612",
			"voltageKv": 275,
			"secondaryVoltageKv": 77,
			"availableCapacityMw": null,
			"operatingCapacityMw": 47,
			"equipmentCapacityMw": 91,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "可。N-1電制適用可能量=44MW。上位系設備=変1、送170、送180。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 34.064837,
				"lon": 136.206437
			},
			"distanceFromTargetKm": 99.368
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "矢の浜変電所",
			"facilityNo": "3748",
			"voltageKv": 77,
			"secondaryVoltageKv": 6.6,
			"availableCapacityMw": 16,
			"operatingCapacityMw": 19,
			"equipmentCapacityMw": 19,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃３。上位系設備=変1、送170、送180。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 34.065281,
				"lon": 136.204891
			},
			"distanceFromTargetKm": 99.37
		},
		{
			"powerArea": "中部電力",
			"prefecture": "三重県",
			"operator": "中部電力パワーグリッド",
			"facilityName": "賀田変電所",
			"facilityNo": "3747",
			"voltageKv": 77,
			"secondaryVoltageKv": 6.6,
			"availableCapacityMw": 9,
			"operatingCapacityMw": 9,
			"equipmentCapacityMw": 19,
			"status": "公表値候補。運用容量制約要因=熱容量。平常時出力制御の可能性=有り。",
			"nMinusOne": "不可 ＃３。上位系設備=変1、送170、送180。",
			"updatedAt": "2026-06-08",
			"sourceUrl": "https://gridmap.powergrid.chuden.co.jp/geo_data/KRSIH013",
			"mapCoordinates": {
				"lat": 33.974585,
				"lon": 136.179634
			},
			"distanceFromTargetKm": 109.657
		}
	],
	"nearestGridFeatures": [
		{
			"name": "30783900-0",
			"facilityNo": "",
			"voltageKvText": "77kV",
			"type": "LineString",
			"distanceFromTargetKm": 0.776,
			"nMinusOne": ""
		},
		{
			"name": "北勢末広-1",
			"facilityNo": "31484",
			"voltageKvText": "77kV",
			"type": "LineString",
			"distanceFromTargetKm": 0.863,
			"nMinusOne": "42 MW"
		},
		{
			"name": "北勢末広-2",
			"facilityNo": "31483",
			"voltageKvText": "77kV",
			"type": "LineString",
			"distanceFromTargetKm": 0.919,
			"nMinusOne": "42 MW"
		},
		{
			"name": "北勢大治田町-1",
			"facilityNo": "31741",
			"voltageKvText": "77kV",
			"type": "LineString",
			"distanceFromTargetKm": 1.998,
			"nMinusOne": "- MW"
		},
		{
			"name": "30750700-0",
			"facilityNo": "",
			"voltageKvText": "154kV",
			"type": "LineString",
			"distanceFromTargetKm": 2.084,
			"nMinusOne": ""
		},
		{
			"name": "南勢北勢線ｰ4",
			"facilityNo": "30034",
			"voltageKvText": "154kV",
			"type": "LineString",
			"distanceFromTargetKm": 2.355,
			"nMinusOne": "0 MW"
		},
		{
			"name": "神戸分岐",
			"facilityNo": "31190",
			"voltageKvText": "77kV",
			"type": "LineString",
			"distanceFromTargetKm": 2.39,
			"nMinusOne": "77 MW"
		},
		{
			"name": "北勢末広-3",
			"facilityNo": "31482",
			"voltageKvText": "77kV",
			"type": "LineString",
			"distanceFromTargetKm": 2.39,
			"nMinusOne": "42 MW"
		},
		{
			"name": "北勢庄野-2",
			"facilityNo": "31174",
			"voltageKvText": "77kV",
			"type": "LineString",
			"distanceFromTargetKm": 2.428,
			"nMinusOne": "129 MW"
		},
		{
			"name": "神戸変電所",
			"facilityNo": "3703",
			"voltageKvText": "77kV",
			"type": "Point",
			"distanceFromTargetKm": 2.524,
			"nMinusOne": "- MW"
		},
		{
			"name": "北勢庄野-4",
			"facilityNo": "31171",
			"voltageKvText": "77kV",
			"type": "LineString",
			"distanceFromTargetKm": 2.549,
			"nMinusOne": "178 MW"
		},
		{
			"name": "北勢庄野-3",
			"facilityNo": "31172",
			"voltageKvText": "77kV",
			"type": "LineString",
			"distanceFromTargetKm": 2.552,
			"nMinusOne": "178 MW"
		},
		{
			"name": "石薬師分岐",
			"facilityNo": "32290",
			"voltageKvText": "77kV",
			"type": "LineString",
			"distanceFromTargetKm": 2.556,
			"nMinusOne": "59 MW"
		},
		{
			"name": "石薬師変電所",
			"facilityNo": "3701",
			"voltageKvText": "77kV",
			"type": "Point",
			"distanceFromTargetKm": 2.583,
			"nMinusOne": "- MW"
		},
		{
			"name": "岸田分岐-1",
			"facilityNo": "31182",
			"voltageKvText": "77kV",
			"type": "LineString",
			"distanceFromTargetKm": 2.599,
			"nMinusOne": "92 MW"
		},
		{
			"name": "北勢大治田町-2",
			"facilityNo": "31740",
			"voltageKvText": "77kV",
			"type": "LineString",
			"distanceFromTargetKm": 2.715,
			"nMinusOne": "- MW"
		},
		{
			"name": "30775200-0",
			"facilityNo": "",
			"voltageKvText": "77kV",
			"type": "LineString",
			"distanceFromTargetKm": 2.716,
			"nMinusOne": ""
		},
		{
			"name": "四港末広-2",
			"facilityNo": "34041",
			"voltageKvText": "22kV",
			"type": "LineString",
			"distanceFromTargetKm": 3.054,
			"nMinusOne": "- MW"
		},
		{
			"name": "大治田町変電所",
			"facilityNo": "3704",
			"voltageKvText": "77kV",
			"type": "Point",
			"distanceFromTargetKm": 3.079,
			"nMinusOne": "- MW"
		},
		{
			"name": "大治田町楠-1",
			"facilityNo": "32121",
			"voltageKvText": "77kV",
			"type": "LineString",
			"distanceFromTargetKm": 3.085,
			"nMinusOne": "- MW"
		}
	],
	"mode": "all"
} as const;
